<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
      <PackageId>LiangTianLin.EFCore.BulkExtensions.Oracle</PackageId>
      <Version>1.1.2</Version>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Oracle.EntityFrameworkCore" Version="8.23.70" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EFCore.BulkExtensions.Core\EFCore.BulkExtensions.Core.csproj" />
  </ItemGroup>

</Project>
